[package]
name        = "orbit64"
description = "Canonical URL-safe encoding for NxNxN cube states, moves, and algorithm DAGs"
version     = "0.8.2"
repository  = "github:wstein/flix-orbit64"
modules     = ["Orbit64"]
flix        = "0.75.2"
license     = "Apache-2.0"
authors     = ["Werner Stein"]
