[package]
name        = "cli-tool"
description = "test"
version     = "0.1.0"
flix        = "0.75.3"
authors     = ["John Doe <john@example.com>"]

[dependencies]
"github:wstein/flix-orbit64" = "0.3.0"